name: Run Tests

on:
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Docker
      run: |
        docker --version
        docker-compose --version

    - name: Build Docker image
      run: |
        make build

    - name: Start container
      run: |
        make up

    - name: Wait for app to initialize
      run: |
        sleep 5  # o reemplázalo con un healthcheck si tienes uno en docker-compose

    - name: Run tests inside container
      run: |
        docker exec rtsp_websocket_api bash -c "PYTHONPATH=. pytest tests/"

    - name: Stop container
      run: |
        make stop
